language: php

php:
    #- 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    #- hhvm
    - nightly



sudo: false



git:
    submodules: false



addons:
    apt:
        packages:
            #- php-codesniffer
            #- phpmd
            #- shellcheck



matrix:
    allow_failures:
        - php: "nightly"



before_script:
    - make install



script:
    - make test



notifications:
    irc: "irc.freenode.org#dbwebb"

    webhooks:
        urls:
            - https://webhooks.gitter.im/e/1da19be791078d3b7fff

        # options: [always|never|change] default: always
        on_success: change
        on_failure: always
        on_start: never
